name: flutter_application_2
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.0  # Added intl package for date formatting
  http: ^1.1.0
  # animation library
  confetti: ^0.8.0
  # audio player library
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  
  # Add assets here if needed
  # Example:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # If you're using custom fonts, define them here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  assets:
    - assets/sounds/ringtone.mp3

flutter_icons:
  android: true                # Enable for Android
  ios: true                    # Enable for iOS
  image_path: "assets/icon/study_steady_icon.png"